### ISSUE TITLE
org file export to xmind?

### ISSUE THREAD

**Issue by linchen2chris** [akirak/xmind-org-el#3]
is it possible convert org file to xmind?

**Comment by akirak** [comment]
No, it is not supported. Technically, it is possible to parse an Org file and emit an XML, but I personally don't have a need for that.

**Comment by akirak** [comment]
The point is that there would be almost no common logic between the two directions. If there is no reusable code, it should be a separate project. I think Org -> XMind (or anything) should be implemented as an org-export backend. Producing a visual mindmap involves styling, so that would require more work than XMind -> Org.
